### ISSUE TITLE
Мы даем ссылки на сайты Циферблатов из ziferblat.net/contacts?

### ISSUE THREAD

**Issue by serge-the-hedge** [esseswann/ziferblat-static#12]
Кажется логичным это делать. Если делаем, покежь пример, откуда именно.

**Comment by daler-als** [comment]
Вся строка ссылка, она уже обернута в тег <a>.

**Comment by serge-the-hedge** [comment]
Ага, то есть href нужно добавить?
В реальные ссылки вы их обернете или мне?

**Comment by daler-als** [comment]
Если можешь добавить href, будет супер. Это уже и будут реальные ссылки

**Comment by serge-the-hedge** [comment]
> Это уже и будут реальные ссылки
Я имел в виду, нужно ли проставлять для этого именно href и если нужно, то мне ли. Это касается и остальных ссылок. Давайте их проставлю я, попозже.

**Comment by daler-als** [comment]
Да, нужны именно href. Спасибо.
