### ISSUE TITLE
Доработать «Главную» для разных разрешений

### ISSUE THREAD

**Issue by serge-the-hedge** [esseswann/ziferblat-static#14]
Насколько я могу судить, сейчас верстка на главной относительно прилично выглядит на «низких» экранах, а чем больше экран в высоту, тем хуже (см. скрины).

На компьютере с средним разрешением вокруг вступительного текста много пустого места

![2017-03-21 1 14 47](https://cloud.githubusercontent.com/assets/5702925/24124238/d6398082-0dd3-11e7-874a-ec2e0a16783d.png)

На телефоне с ретиной просто привет, пиздец.

![aiqvb-uxu70](https://cloud.githubusercontent.com/assets/5702925/24124262/f098357c-0dd3-11e7-8a00-6dae29eaaa0f.jpg)

В то же время есть ощущение, что каждая картинка / гифка в отдельности маленькая, на них сложно что-нибудь разобрать.

Может быть, часть проблем можно поправить изменением размера изображений в зависимости от размера экрана? Или нет?

**Comment by daler-als** [comment]
Первая картинка уже поправлена. Остальное поправлю.

**Comment by serge-the-hedge** [comment]
Супер, но кажется, идеальное решение все еще не найдено :-)

![2017-03-21 9 38 34](https://cloud.githubusercontent.com/assets/5702925/24135438/bf8f87cc-0e1a-11e7-8103-9f1c1c45c99b.png)

На скрине загораживается часть текста (может быть, это ОК, но чуть меньше все же?) и отъехали элементы от края следующего блока. Кажется, один из ходов, который может улучшить ситуацию, — не обрубать так изображения, чтобы они теоретически существовали, но были от нас загорожены следующим блоком. Все равно большинство разрешений нужно будет настроить вручную для красивого отображения, но при таком раскладе даже в случае дичайшего бага не будет обрубков элементов. Если я не прав, игнорируй.

**Comment by daler-als** [comment]
Не, ты прав. Я имел в виду поправлено для больших разрешений. Остальные на полпути.

**Comment by serge-the-hedge** [comment]
@daler-als @esseswann чего здесь с попутем?

**Comment by esseswann** [comment]
Насколько я могу судить это исправлено

**Comment by daler-als** [comment]
Вроде норм.
