### ISSUE TITLE
Нижние блоки на мобилах ставить друг за другом

### ISSUE THREAD

**Issue by daler-als** [esseswann/ziferblat-static#15]
Арсений, сейчас нижние блоки схлопываются. Можешь сделать, пожалуйста, чтобы они просто шли друг за другом?

**Comment by esseswann** [comment]
Нижние блоки где?

**Comment by daler-als** [comment]
Сорри, на главной странице.

**Comment by serge-the-hedge** [comment]
![2017-06-06 14 36 55](https://cloud.githubusercontent.com/assets/5702925/26827450/fcfca13e-4ac5-11e7-8096-a7689876539f.png)

@daler-als не находишь, что странно выровнен по вертикали блок про сми?

**Comment by esseswann** [comment]
Давайте добавим в него картинку и будет норм

**Comment by daler-als** [comment]
Давай перед лейблом СМИ уберем 10 пикселей, после лейбла уберем 20 пикселей. После логотип надо сделать 40 пикселей.

**Comment by daler-als** [comment]
Сделали.
