### ISSUE TITLE
Поправить блок Как стать партнером

### ISSUE THREAD

**Issue by daler-als** [esseswann/ziferblat-static#20]
Можем его сделать такой же плиткой, как в списке Ц? И чтобы когда там появляется пустое место размерами с два блока, он занимал всю площадь?

**Comment by esseswann** [comment]
Я сделал так чтобы он занимал пространство, но рекомендую
а) добавить внятное разделение междуциферблатами и подвалом
б) добавить в него всё-таки ссылку или кнопку

Кроме того следует учитывать что когда количество циферблатов кратно трём он будет всё равно перекладину занимать
