### ISSUE TITLE
Сверстать страницу экспертности

### ISSUE THREAD

**Issue by daler-als** [esseswann/ziferblat-static#23]
Арсений, нужно сверстать эту страницу в наших стилях: https://readymag.com/ziferblat/develop/.

Предлагаю для начала сделать следующее:
1. Перенести страницу
2. Выровнять по сетке
3. Применить стили
4. Добавить шапку и подвал

**Comment by esseswann** [comment]
:briefcase:

**Comment by serge-the-hedge** [comment]
@daler-als сможешь сделать новую шапку? Сейчас Иисус использует рандомные картинки, но у меня нет исходников тех, что были в Редимаге. Кроме того, я не уверен, что они подходят по стилистике и такая верстка хорошо оптимизируется для маленьких разрешений. Можешь проверить и предложить окончательное решение?

**Comment by serge-the-hedge** [comment]
@esseswann здесь пока не закончено?

**Comment by daler-als** [comment]
Я предлагаю пока просто вот так сделать: 
— без шапки с картинкой; 
— выровнять все по левому краю;
— стили форм взять от этой анкеты — http://static.ziferblat.net/partnership.html.
![expert](https://cloud.githubusercontent.com/assets/6771479/26765312/2dfbbad0-4982-11e7-8fe7-dec1b32e6c3c.png)

**Comment by serge-the-hedge** [comment]
Супер!
