### ISSUE TITLE
Главная / Последние блоки / Айфон 5

### ISSUE THREAD

**Issue by daler-als** [esseswann/ziferblat-static#24]
Предлагаю пока так расположить блоки в подвале на мобилах:
![group](https://cloud.githubusercontent.com/assets/6771479/26023721/69e8b4da-37cb-11e7-92cf-6cb8b70bc33b.png)

**Comment by daler-als** [comment]
Шрифт на этой картинке - Робото.

**Comment by serge-the-hedge** [comment]
@esseswann чего как?
