### ISSUE TITLE
Поправить поведение логотипа при уменьшении ширины окна

### ISSUE THREAD

**Issue by serge-the-hedge** [esseswann/ziferblat-static#5]
Сейчас она выглядит странно.

![2017-03-16 20 59 52](https://cloud.githubusercontent.com/assets/5702925/24011556/2c341eca-0a8c-11e7-8459-d27de78e616d.png)

![2017-03-16 20 59 46](https://cloud.githubusercontent.com/assets/5702925/24011559/2c6bce56-0a8c-11e7-9e89-f0d39723b49d.png)

**Comment by daler-als** [comment]
Арсений, можно просто под логотип скидывать меню.
