### ISSUE TITLE
Подкрутить поведение блока «Как открыть Циферблат» при ресайзе

### ISSUE THREAD

**Issue by serge-the-hedge** [esseswann/ziferblat-static#7]
«И» не разговариаает с «прибылью».
Обмен опытом пытается сбежать.

![2017-03-16 20 57 43](https://cloud.githubusercontent.com/assets/5702925/24011717/965f6ac0-0a8c-11e7-83ce-5066790fb608.png)

Мы его упустили.

![2017-03-16 20 58 56](https://cloud.githubusercontent.com/assets/5702925/24011744/b174910a-0a8c-11e7-8d57-a117d236289e.png)

**Comment by daler-als** [comment]
Не успел закоммитить новый вид блока. Текста в самой статье стало меньше, поэтому предлагаю не делить ее на главы в Партнерстве и здесь. Кажется, что это избытычно.

**Comment by serge-the-hedge** [comment]
Окей, закрыва тогда.
