### ISSUE TITLE
Избавиться от пустого блока в списке Циферблатов

### ISSUE THREAD

**Issue by serge-the-hedge** [esseswann/ziferblat-static#9]
Смущает прилипание к пунктирной линии и пустоты с боков последнего Циферблата в списке. Тебе не кажется этот момент лапотным?

![2017-03-16 20 59 20](https://cloud.githubusercontent.com/assets/5702925/24011887/1fe530e0-0a8d-11e7-90a9-4d8a13f6688d.png)

**Comment by daler-als** [comment]
Ну да.

**Comment by daler-als** [comment]
Арсений, можешь так?
![default](https://cloud.githubusercontent.com/assets/6771479/26023942/f9cb98de-37cf-11e7-9952-e8377a71e9d9.png)

**Comment by serge-the-hedge** [comment]
@esseswann как здесь успехи?
